import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/navbar/navbar";
import { Jost } from "next/font/google";
import Footer from "@/app/components/footer/footer";
const inter = Inter({ subsets: ["latin"] });
// const jost = Jost({ subsets: ['latin'] })
import { ContextProvider } from "./context/myContext";
export const metadata: Metadata = {
  title: "Web-Shoes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="no-scrollbar ">
        <ContextProvider>
          <Navbar />
          {children}
          <Footer />
        </ContextProvider>
      </body>
    </html>
  );
}
