import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/navbar/navbar'
import { Jost } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
// const jost = Jost({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Web-Shoes',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className = 'no-scrollbar'>
        <Navbar/>
        {children}
        </body>
    </html>
  )
}
