export const productData = [
  {
    id: 1,
    title: "Nike Air Max",
    desc: "Air Max shoes are identified by their midsoles incorporating flexible urethane pouches filled with pressurized gas",
    price: 100.99,
    sizes: [
      { size: 39, stock: 5 },
      { size: 40, stock: 10 },
      { size: 41, stock: 2 },
      { size: 42, stock: 0 },
      { size: 43, stock: 20 },
      { size: 44, stock: 0 },
    ],
  },
  {
    id: 2,
    title: "Nike Air Force 1",
    desc: "This pair of Nike sneakers represents a modern take on a classic. The Air Force 1 model comes in a variety of styles.",
    price: 200.99,
    sizes: [
      { size: 39, stock: 5 },
      { size: 40, stock: 10 },
      { size: 41, stock: 2 },
      { size: 42, stock: 0 },
      { size: 43, stock: 20 },
      { size: 44, stock: 0 },
    ],
    // sizes: [
    //   "39","40","41","42","43","44"
    // ],
    // quantity:[{"39": 5},
    // {"40": 5},
    // {"41": 5},
    // {"42": 5},
    // {"43": 5},]
  },
  {
    id: 3,
    title: "Adidas NMD R1",
    desc: "These breathable sneakers from Adidas are inspired by the trends of the '80s kid's.",
    price: 300.99,
    sizes: [
      { size: 39, stock: 5 },
      { size: 40, stock: 10 },
      { size: 41, stock: 2 },
      { size: 42, stock: 0 },
      { size: 43, stock: 20 },
      { size: 44, stock: 0 },
    ],
  },
  {
    id: 4,
    title: "Air Jordan 4 Retro",
    desc: "The Air Jordan 4 was the first global release of the Jordan brand and was originally released as a tribute. ",
    price: 400.99,
    sizes: [
      { size: 39, stock: 5 },
      { size: 40, stock: 10 },
      { size: 41, stock: 2 },
      { size: 42, stock: 0 },
      { size: 43, stock: 20 },
      { size: 44, stock: 0 },
    ],
  },
  {
    id: 5,
    title: "Adidas Yeezy V2",
    desc: "Yeezy sales were overall down against 2018 for the year, but this 2017 model made the top sellers list.",
    price: 500.99,
    sizes: [
      { size: 39, stock: 5 },
      { size: 40, stock: 10 },
      { size: 41, stock: 2 },
      { size: 42, stock: 0 },
      { size: 43, stock: 20 },
      { size: 44, stock: 0 },
    ],
  },
  {
    id: 6,
    title: "Vans Ward",
    desc: "One of the most popular skate shoes, the Ward Low Top from Vans features an iconic side stripe.",
    price: 600.99,
    sizes: [
      { size: 39, stock: 5 },
      { size: 40, stock: 10 },
      { size: 41, stock: 2 },
      { size: 42, stock: 0 },
      { size: 43, stock: 20 },
      { size: 44, stock: 0 },
    ],
  },
  {
    id: 7,
    title: "Converse OX Low",
    desc: "Probably one of the most classic sneakers of all time, the Chuck Taylor All Stars are available.",
    price: 700.99,
    sizes: [
      { size: 39, stock: 5 },
      { size: 40, stock: 10 },
      { size: 41, stock: 2 },
      { size: 42, stock: 0 },
      { size: 43, stock: 20 },
      { size: 44, stock: 0 },
    ],
  },
  {
    id: 8,
    title: "Nike Air Max 97 ",
    desc: "The water-ripple line design of the Nike Air Max 97 makes this sneaker iconic.",
    price: 800.99,
    sizes: [
      { size: 39, stock: 5 },
      { size: 40, stock: 10 },
      { size: 41, stock: 2 },
      { size: 42, stock: 0 },
      { size: 43, stock: 20 },
      { size: 44, stock: 0 },
    ],
  },
  {
    id: 9,
    title: "Jordan 11 Retro",
    desc: "The Air Jordan 11 collection was originally released in 1995 and appeared in the 1996 animated film 'Space Jam'.",
    price: 900.99,
    sizes: [
      { size: 39, stock: 5 },
      { size: 40, stock: 10 },
      { size: 41, stock: 2 },
      { size: 42, stock: 0 },
      { size: 43, stock: 20 },
      { size: 44, stock: 0 },
    ],
  },

  {
    id: 10,
    title: "Nike Tanjun",
    desc: "The Tanjun, which gets its name from the Japanese word for 'simplicity,' comes in a variety of colors.",
    price: 1000.99,
    sizes: [
      { size: 39, stock: 5 },
      { size: 40, stock: 10 },
      { size: 41, stock: 2 },
      { size: 42, stock: 0 },
      { size: 43, stock: 20 },
      { size: 44, stock: 0 },
    ],
  },
];

export const methodData = [
  {
    id: 1,
    company: "Fedex Delivery 1",
    delivery: " 2-4days",
  },
  {
    id: 2,
    company: "Fedex Delivery 2",
    delivery: " 3-7days",
  },
];
